import Head from "next/head"
import Image from "next/image"
import Slider from "@/components/home/Slider"
import ServiceCard from "@/components/home/ServiceCard"
import Services from "@/components/home/Services"

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={"bg-light dark:bg-dark text-pri"}>
                {/*     Home Hero Slider     */}
                <Slider />
                {/*   List Down Services   */}
                <Services />
            </main>
        </>
    )
}
