import Head from "next/head";
import Image from "next/image";
import Slider from "@/components/home/Slider";
import ServiceCard from "@/components/home/ServiceCard";
import Services from "@/components/home/Services";
import { LinkButton } from "@/components/button/Button";
import useUser from "@/store/useUser";

export default function Home() {
  const { user } = useUser();
  console.log("user : " + user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"bg-light dark:bg-dark text-pri"}>
        {user?.role == "user" || user?.role == null ? (
          <div>
            {/*     Home Hero Slider     */}
            <Slider />
            {/*   List Down Services   */}
            <Services />
          </div>
        ) : (
          <div className="min-h-screen flex justify-center items-center ">
            <LinkButton link="/requests" children="Go to Requests" />
          </div>
        )}
      </main>
    </>
  );
}
